name: Sync to HuggingFace 🤗 hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf-hub:
    runs-on: ubuntu-latest

    steps:
      - name: 🤗 HF Space Sync
        uses: e-alizadeh/gh-actions/hf-space-sync@main
        with:
          hf_user:  "ealizadeh"
          hf_space: "GAIA-Agent"
          hf_token: ${{ secrets.HF_TOKEN }}
